openai_api_key = "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"

[db_credentials]
host = "default-workgroup.019915518575.eu-central-1.redshift-serverless.amazonaws.com"
port = 5439
username = "sample_user"
password = "Analitiq1234"
database = "dev"
schema = "public"
